In [3]:
import numpy as np

# Array indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array indexing:")
print("arr[2]: ", arr[2])  # Accessing the element at index 2
print("arr[1:4]", arr[1:4])  # Accessing a slice of elements from index 1 to 3

# Fancy indexing
print("\nFancy indexing:")
indices = np.array([0, 2, 4])  # Array of indices
print("arr[indices]", arr[indices])  # Accessing elements at the specified indices

Array indexing:
arr[2]:  3
arr[1:4] [2 3 4]

Fancy indexing:
arr[indices] [1 3 5]


In [2]:
import numpy as np

# Create a sample 2D NumPy array
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])


# Display the original array
print("Original Array:")
print(data)

# Slicing the array
# Syntax: array[row_start:row_end, col_start:col_end]

# Selecting a single row (row 1)
row_1 = data[1, :]
print("\nRow 1:")
print(row_1)

# Selecting a single column (column 2)
col_2 = data[:, 2]
print("\nColumn 2:")
print(col_2)

# Slicing a subarray (rows 0 and 1, columns 1 and 2)
subarray1 = data[0:2, 1:3]
print("\nSubarray1 (rows 0:2, columns 1:3):")
print(subarray1)

# Slicing with step (every other row, every other column)
step_slice = data[::2, ::2]
print("\nStep Slice (every other row, every other column):")
print(step_slice)

subarray2= data[1:3, 2:4]
print("\nSubarray2 (rows 1:3, columns 2:4):")
print(subarray2)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Row 1:
[5 6 7 8]

Column 2:
[ 3  7 11]

Subarray1 (rows 0:2, columns 1:3):
[[2 3]
 [6 7]]

Step Slice (every other row, every other column):
[[ 1  3]
 [ 9 11]]

Subarray2 (rows 1:3, columns 2:4):
[[ 7  8]
 [11 12]]


In [4]:
import numpy as np

# Create a 5-dimensional array with shape (2, 3, 4, 5, 6)
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=5)

print("The 5D array", arr)
print("Shape of the array:", arr.shape)

The 5D array [[[[[1 2 3 4 5 6]]]]]
Shape of the array: (1, 1, 1, 1, 6)


In [5]:
import numpy as np

# Create a 1-D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2-D array with 2 rows and 3 columns
arr_2d = np.reshape(arr_1d, (2, 3))

# Display the original and reshaped arrays
print("Original 1-D array:")
print(arr_1d)

print("\nReshaped 2-D array (using reshape):")
print(arr_2d)

Original 1-D array:
[1 2 3 4 5 6]

Reshaped 2-D array (using reshape):
[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays using stack()
stacked_arr = np.stack((arr1, arr2))
print("Stacked array:")
print(stacked_arr)

# Stack arrays horizontally using hstack()
hstacked_arr = np.hstack((arr1, arr2))
print("\nHorizontally stacked array:")
print(hstacked_arr)

# Stack arrays vertically using vstack()
vstacked_arr = np.vstack((arr1, arr2))
print("\nVertically stacked array:")
print(vstacked_arr)


# Create two 2D arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Stack arrays along the third axis using dstack()
dstacked_arr = np.dstack((arr3, arr4))
print("\nDepth-wise stacked array:")
print(dstacked_arr)

Stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]

Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Depth-wise stacked array:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
import numpy as np

# Create a numpy array
arr = np.array(['syringe', 'stethoscope', 'catheter', 'thermometer', 'scalpel', 'forcep', 'stretcher', 'otoscope'])

#Sort the array in ascending order
sorted_array = np.sort(arr)
print("Sorted Array (ascending order):")
print(sorted_array)

# Sort the array in descending order
reverse_sorted_array = np.sort(arr)[::-1]
print("\nSorted Array (descending order):")
print(reverse_sorted_array)


# Perform a binary search to find the position to insert a value while maintaining the sorted order
value_to_insert = 'nebulizer'
position_to_insert = np.searchsorted(sorted_array, value_to_insert)
print(f"\nPosition to Insert {value_to_insert} to Maintain Sorted Order:", position_to_insert)

# Perform a binary search to find the indices where a value should be inserted to maintain sorted order
values_to_insert = ['sterilizer', 'mask', 'ventilator']
positions_to_insert = np.searchsorted(sorted_array, values_to_insert)
print("\nPositions to Insert Multiple Values to Maintain Sorted Order:")
print(positions_to_insert)

Sorted Array (ascending order):
['catheter' 'forcep' 'otoscope' 'scalpel' 'stethoscope' 'stretcher'
 'syringe' 'thermometer']

Sorted Array (descending order):
['thermometer' 'syringe' 'stretcher' 'stethoscope' 'scalpel' 'otoscope'
 'forcep' 'catheter']

Position to Insert nebulizer to Maintain Sorted Order: 2

Positions to Insert Multiple Values to Maintain Sorted Order:
[4 2 8]


In [8]:
import pandas as pd

# Create a list of dictionaries
data = [
    {'Name': 'Manoswita', 'Age': 22, 'City': 'Kolkata'},
    {'Name': 'Naina', 'Age': 30, 'City': 'Chennai'},
    {'Name': 'Kareena', 'Age': 27, 'City': 'Bangalore'},
    {'Name': 'Ashima', 'Age': 35, 'City': 'Hyderabad'},
    {'Name': 'Latika', 'Age': 29, 'City': 'Delhi'}
]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

        Name  Age       City
0  Manoswita   22    Kolkata
1      Naina   30    Chennai
2    Kareena   27  Bangalore
3     Ashima   35  Hyderabad
4     Latika   29      Delhi


In [9]:
import pandas as pd

# Creating a DataFrame using Lists
data_list = [['Dr. Arun Chatterjee', 28, 'Cardiologist'],
             ['Dr. Mohan Patel', 32, 'Oncologist'],
             ['Dr. Vikram Singh', 29, 'Urologist']]

columns_list = ['Doctor Name', 'Age', 'Specialization']

df_list = pd.DataFrame(data_list, columns=columns_list)

# Creating a DataFrame using Dictionaries
data_dict = {
    'Doctor Name': ['Dr. Rashid Ali', 'Dr. Karan Saxena', 'Dr. Feroze Hakim'],
    'Age': [33, 27, 31],
    'Occupation': ['Radiologist', 'Gynaecologist', 'Child Specialist']
}

df_dict = pd.DataFrame(data_dict)

# Displaying the DataFrames
print("DataFrame created using Lists:")
print(df_list)

print("\nDataFrame created using Dictionaries:")
print(df_dict)

DataFrame created using Lists:
           Doctor Name  Age Specialization
0  Dr. Arun Chatterjee   28   Cardiologist
1      Dr. Mohan Patel   32     Oncologist
2     Dr. Vikram Singh   29      Urologist

DataFrame created using Dictionaries:
        Doctor Name  Age        Occupation
0    Dr. Rashid Ali   33       Radiologist
1  Dr. Karan Saxena   27     Gynaecologist
2  Dr. Feroze Hakim   31  Child Specialist


In [12]:
import pandas as pd

data = {'Patient_ID': [1, 2, 3, 4, 5],
        'Name': ['Varun', 'Jiya', 'Ishaan', 'Meera', 'Arunesh'],
        'Age': [25, 32, None, 45, 28],
        'Gender': ['Male', 'Female', 'Male', None, 'Male'],
        'Diagnosis': ['Flu', 'Hypertension', 'Diabetes', 'Fever', None],
        'Further_visits_required': [False, True, True, False, False]
        }

df = pd.DataFrame(data)

# Check for missing data

# isnull() - Check if a value is missing (returns a DataFrame of boolean values)
print("\nCheck for Missing Data (isnull()):")
print(df.isnull())

# notnull() - Check if a value is not missing (returns a DataFrame of boolean values)
print("\nCheck for Non-Missing Data (notnull()):")
print(df.notnull())

# dropna() - Remove rows with missing values
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing values (dropna()):")
print(df_dropped)

# fillna() - Fill missing values with a specified value or strategy
df_filled = df.fillna({'age': df['age'].mean(), 'gender': 'Unknown'})
print("\nDataFrame after filling missing values (fillna()):")
print(df_filled)

# replace() - Replace specific values with another value
df_replaced = df.replace({'Further_visits_required': {True: 'Yes', False: 'No'}})
print("\nDataFrame after replacing values (replace()):")
print(df_replaced)

# interpolate() - Interpolate missing values (works well with numeric data)
df_interpolated = df.interpolate()
print("\nDataFrame after interpolating missing values (interpolate()):")
print(df_interpolated)


Check for Missing Data (isnull()):
   Patient_ID   Name    Age  Gender  Diagnosis  Further_visits_required
0       False  False  False   False      False                    False
1       False  False  False   False      False                    False
2       False  False   True   False      False                    False
3       False  False  False    True      False                    False
4       False  False  False   False       True                    False

Check for Non-Missing Data (notnull()):
   Patient_ID  Name    Age  Gender  Diagnosis  Further_visits_required
0        True  True   True    True       True                     True
1        True  True   True    True       True                     True
2        True  True  False    True       True                     True
3        True  True   True   False       True                     True
4        True  True   True    True      False                     True

DataFrame after dropping rows with missing values (dropna()):
  

KeyError: 'age'

In [13]:
import pandas as pd

# Create a sample DataFrame for the online election system
data = {'Patient_ID': [1, 2, 3, 4, 5],
        'Name': ['Varun', 'Jiya', 'Ishaan', 'Meera', 'Arunesh'],
        'Age': [25, 32, None, 45, 28],
        'Gender': ['Male', 'Female', 'Male', None, 'Male'],
        'Diagnosis': ['Flu', 'Hypertension', 'Diabetes', 'Fever', None],
        'Further_visits_required': [False, True, True, False, False]
        }

df = pd.DataFrame(data)

# Create hierarchical indexing with 'voter_id' and 'voter_name'
df.set_index(['Patient_ID', 'Name'], inplace=True)

# Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)

DataFrame with Hierarchical Indexing:
                     Age  Gender     Diagnosis  Further_visits_required
Patient_ID Name                                                        
1          Varun    25.0    Male           Flu                    False
2          Jiya     32.0  Female  Hypertension                     True
3          Ishaan    NaN    Male      Diabetes                     True
4          Meera    45.0    None         Fever                    False
5          Arunesh  28.0    Male          None                    False
